# Generated by Django 4.0.4 on 2022-04-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_building_faculty_speciality_teacher_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField()),
                ('num', models.IntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.faculty')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.speciality')),
            ],
        ),
    ]
