# Generated by Django 4.0.4 on 2022-04-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auditory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('lesson_type', models.CharField(max_length=200)),
                ('auditory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.auditory')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.group')),
                ('id_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subject')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.time')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.teacher')),
            ],
        ),
    ]
