# Generated by Django 4.0.4 on 2022-05-01 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_course_group_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.faculty'),
        ),
    ]
