# Generated by Django 4.0.4 on 2022-05-01 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_speciality_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.day')),
            ],
        ),
    ]
