# Generated by Django 4.0.4 on 2022-05-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_day_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='week',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
