# Generated by Django 4.0.4 on 2022-05-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_week_week_delete_day_delete_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='id_name',
        ),
    ]
