# Generated by Django 4.0.4 on 2022-05-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_schedule_date_day_schedule_alter_day_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
