# Generated by Django 4.0.4 on 2022-05-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='auditory',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='group',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='id_name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lesson_type',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
    ]
