# Generated by Django 4.0.4 on 2022-05-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_schedule_auditory_remove_schedule_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditory',
            name='building',
        ),
        migrations.RemoveField(
            model_name='auditory',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='auditory',
            name='num_auditory',
        ),
        migrations.RemoveField(
            model_name='building',
            name='address',
        ),
        migrations.RemoveField(
            model_name='building',
            name='enclosure',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='group',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='group',
            name='num',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='group',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='group',
            name='year',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='name',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='time',
            name='begin',
        ),
        migrations.RemoveField(
            model_name='time',
            name='ending',
        ),
    ]
