# Generated by Django 4.0.4 on 2022-05-01 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_auditory_building_remove_auditory_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditory',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.building'),
        ),
        migrations.AddField(
            model_name='auditory',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditory',
            name='num_auditory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='enclosure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.faculty'),
        ),
        migrations.AddField(
            model_name='group',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.speciality'),
        ),
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='auditory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.auditory'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.group'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subject'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lesson_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.teacher'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.faculty'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='begin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='ending',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
