# Generated by Django 4.0.4 on 2022-05-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_day_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='xui',
            field=models.DateField(blank=True, null=True),
        ),
    ]
