# Generated by Django 4.0.4 on 2022-05-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_schedule_options_rename_name_teacher_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='desc',
        ),
        migrations.AddField(
            model_name='teacher',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
